platform :ios, '9.0'
use_frameworks!
source 'sso://cpdc-test/firebase-ml'
source 'sso://cpdc-internal/firebase'
source 'https://github.com/CocoaPods/Specs.git'

pod 'FirebaseCore'
pod 'FirebaseMLVision'
pod 'FirebaseMLVisionTextModel'
pod 'FirebaseMLNLLanguageID'
pod 'FirebaseMLNLTranslate'
pod 'MaterialComponents/List'
pod 'MaterialComponents/AppBar'
pod 'MaterialComponents/Chips'
pod 'MaterialComponents/Chips+ChipThemer'
pod 'MaterialComponents'

target 'TranslateDemo' do
end

