platform :ios, '9.0'
use_frameworks!

pod 'Firebase/MLVision'
pod 'Firebase/MLVisionTextModel'
pod 'Firebase/MLNLLanguageID'
pod 'Firebase/MLNLTranslate'
pod 'MaterialComponents/List'
pod 'MaterialComponents/AppBar'
pod 'MaterialComponents/Chips'
pod 'MaterialComponents/Chips+ChipThemer'
pod 'MaterialComponents'

target 'TranslateDemo' do
end

